# Generated by Django 4.2.16 on 2024-11-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at", "-completed"]},
        ),
    ]
