# Generated by Django 4.2.16 on 2024-11-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="todo.tag"
            ),
        ),
    ]
